export interface MenuItem {
  label: string;   // Texto visible: "Inicio", "Mis Calificaciones"...
  icon: string;    // Clase del icono de Bootstrap: "bi-house-door"
  route: string;   // Ruta hija: "inicio", "calificaciones"...
}